name: grocerystacked
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  country_flags: ^2.2.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  intl_phone_number_input: ^0.7.4
  shared_preferences: ^2.2.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/