// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgkpE121gTsAq2dDZKuGxbSpA83fW8ia4',
    appId: '1:541473713516:web:16ddf523e98f7b417c9749',
    messagingSenderId: '541473713516',
    projectId: 'grocery-2cfa5',
    authDomain: 'grocery-2cfa5.firebaseapp.com',
    storageBucket: 'grocery-2cfa5.appspot.com',
    measurementId: 'G-W2HCDBQM4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF0KIyh7hYEWDqTuGmvAkMR0qgFrBroRA',
    appId: '1:541473713516:android:0170ad24ea43ac377c9749',
    messagingSenderId: '541473713516',
    projectId: 'grocery-2cfa5',
    storageBucket: 'grocery-2cfa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ZSBImT86rHipLn8OG5s8NWR1fxQKUaI',
    appId: '1:541473713516:ios:ea698dcda77713cf7c9749',
    messagingSenderId: '541473713516',
    projectId: 'grocery-2cfa5',
    storageBucket: 'grocery-2cfa5.appspot.com',
    iosBundleId: 'com.example.grocerystacked',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ZSBImT86rHipLn8OG5s8NWR1fxQKUaI',
    appId: '1:541473713516:ios:ea698dcda77713cf7c9749',
    messagingSenderId: '541473713516',
    projectId: 'grocery-2cfa5',
    storageBucket: 'grocery-2cfa5.appspot.com',
    iosBundleId: 'com.example.grocerystacked',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgkpE121gTsAq2dDZKuGxbSpA83fW8ia4',
    appId: '1:541473713516:web:367c6a6063e156a87c9749',
    messagingSenderId: '541473713516',
    projectId: 'grocery-2cfa5',
    authDomain: 'grocery-2cfa5.firebaseapp.com',
    storageBucket: 'grocery-2cfa5.appspot.com',
    measurementId: 'G-W72JRFPMNV',
  );

}